### ISSUE TITLE
issues with nix-build -o smash-local and derivations not materialized

### ISSUE THREAD

**Issue by TrevorBenson** [input-output-hk/smash#104]
I always seem to get the following errors when trying to perform `nix-build -o smash-local`:

```
trace: Using index-state: 2020-07-15T00:00:00Z for smash-src
trace: Using index-state: 2020-05-31T00:00:00Z for hoogle
trace: To make this a fixed-output derivation but not materialized, set `plan-sha256` to the output of /nix/store/59xzij961smp4lp3rc2483rcjlbq7ysl-calculateSha
trace: To materialize the output entirely, pass a writable path as the `materialized` argument and pass that path to /nix/store/5jjli8cwi1593s5vq4gcyqjf5cw2ysyi-generateMaterialized
/nix/store/k4akaqbi4wc31aqi3nlsak3r5d71nsdq-smash-test-smash-test-1.1.0-check
/nix/store/ryyh49wck7krfmc3c30d2wfx50gg27hf-smash-exe-smash-exe-1.1.0
/nix/store/7rbrqpdq2kp61qvqs5qj1jx70wmasnc5-smash-lib-smash-1.1.0
/nix/store/gf3c9b3qv9i5mz1176c34xj1bb0pyaf5-smash-test-smash-test-1.1.0
/nix/store/n47kv00bv1sfznnr6snwbp5gpysd7blj-default-Setup-setup
/nix/store/xnrch821xylf9sk696xqqzciwgrhqr94-cabal-dev-shell
```

I also tried:

- building from the master branch for smash instead of 1.1.0 tag
- building smash from inside cardano-node repository after successf nix-build of version 1.19.0 and version 1.21.1. 
- nix-collect-garbage after each failed build attempt and then rebuilt.
- cabal update and rebuilding each repository branch/tag.
- Use instructions from [https://input-output-hk.github.io/haskell.nix/tutorials](https://input-output-hk.github.io/haskell.nix/tutorials/materialization/#how-can-we-materialize-the-nix-files) regarding materialization. I'm not familiar enough with nix file syntax to determine where in default.nix I would place a materialized parameter or how to modify the inherit lines to allow it.
  - Regardless neither the `/nix/store/59xzij961smp4lp3rc2483rcjlbq7ysl-calculateSha` or `/nix/store/5jjli8cwi1593s5vq4gcyqjf5cw2ysyi-generateMaterialized` paths currently exist, so could not be copied to smash.materialized directory even if I understood the syntax & adjusted the file accordingly.

I get the same errors shown when building smash from repository master and 1.1.0. I get a different error (not shown) when building smash directly from cardano-node repository.

** Additional Details ** 

I'm attempting to follow the current smash instructions but using a current OS (CentOS 8 in this instance). The current prerequisite instructions are for Ubuntu 14.04, as `libpq-dev` package does not exist in Ubuntu 16.04, 18.04 or 20.04 releases and I am not going to use an OS that is 3 LTS releases behind (6 years old), EOS  and soon to be EOL. I can resolve the postgres development packages easily, so do not have any reason to believe the OS choice is related to the errors. I am however open to trying Ubuntu 14.04 if there is confidence that this is an OS level issue, but certainly does not appear to be to me.

**Comment by TrevorBenson** [comment]
I forgot to mention that ignoring the error and moving onto the following steps of `SMASHPGPASSFILE=config/pgpass ./smash-local run-migrations --mdir ./schema` returns:

```
$ SMASHPGPASSFILE=config/pgpass ./smash-local run-migrations --mdir ./schema
-bash: ./smash-local: Permission denied
```

Changing the file to be executable causes the following:

```
$ chmod +x /nix/store/y53jr5mrmnxn7iinffz6l2dii0vm3y8l-smash-test-smash-test-1.1.0-check
$ SMASHPGPASSFILE=config/pgpass ./smash-local run-migrations --mdir ./schema
./smash-local: line 2: SMASH: command not found
./smash-local: line 3: DataLayer: command not found
./smash-local: line 4: Delisted: command not found
./smash-local: line 5: should: command not found
./smash-local: line 7: SMASH: command not found
./smash-local: line 8: SMASH: command not found
./smash-local: line 9: HULK: command not found
./smash-local: line 10: +++: command not found
./smash-local: line 11: 100%: command not found
./smash-local: line 13: syntax error near unexpected token `('
./smash-local: line 13: `       5% [("InsertPool",88)]'
```

**Comment by TrevorBenson** [comment]
Thanks to @disassembler who responded in a Telegram channel and said to to try:
```
nix-build -A haskellPackages.smash.components.exes.smash-exe -o smash-local
``` 
The build succeeds. The smash-local symlink is pointing at the directory of `/nix/store/xxa09a59mb16zbpbpf9crg7l1494pz7k-smash-exe-smash-exe-1.1.0/`. Fixing the symlink to instead link inside the directory to the `bin/smash-exe` file:
```
$ rm smash-local
$ ln -s /nix/store/xxa09a59mb16zbpbpf9crg7l1494pz7k-smash-exe-smash-exe-1.1.0/bin/smash-exe smash-local
```
The run-migration step now succeeds.

Should `-A haskellPackages.smash.components.exes.smash-exe` be added to the documentation?

**Comment by ksaric** [comment]
> Thanks to @disassembler who responded in a Telegram channel and said to to try:
> 
> ```
> nix-build -A haskellPackages.smash.components.exes.smash-exe -o smash-local
> ```
> 
> The build succeeds. The smash-local symlink is pointing at the directory of `/nix/store/xxa09a59mb16zbpbpf9crg7l1494pz7k-smash-exe-smash-exe-1.1.0/`. Fixing the symlink to instead link inside the directory to the `bin/smash-exe` file:
> 
> ```
> $ rm smash-local
> $ ln -s /nix/store/xxa09a59mb16zbpbpf9crg7l1494pz7k-smash-exe-smash-exe-1.1.0/bin/smash-exe smash-local
> ```
> 
> The run-migration step now succeeds.
> 
> Should `-A haskellPackages.smash.components.exes.smash-exe` be added to the documentation?

I will add it into the documentation in the next PR, thanks for the feedback and the investigation :heart:
