### ISSUE TITLE
Expose API types in a separate package

### ISSUE THREAD

**Issue by hasufell** [input-output-hk/smash#110]
Despite my best efforts to improve the building situation and the mock server, it was decided that the wallet won't be building against the whole smash lib for now, which I find sad, because it will mean to build a manual mock server and not be able to test against the real thing for now.

However, we still want to have access to the servant types, so we can call the endpoints nicely as a servant client with minimal dependencies. That'll still be quite useful and I've seen this approach in use in other companies too. I'm preparing a PR right now to split the packages, so you can see how it looks like and if you like it.

**Comment by ksaric** [comment]
Resolved by https://github.com/input-output-hk/smash/pull/112
