### ISSUE TITLE
Provide sum type for PoolId

### ISSUE THREAD

**Issue by hasufell** [input-output-hk/smash#118]
```hs
-- | The stake pool identifier. It is the hash of the stake pool operator's
-- vkey.
--
-- It may be rendered as hex or as bech32 using the @pool@ prefix.
--
newtype PoolId = PoolId { getPoolId :: Text }
```

As the comment inidcates, there may be different encodings. Currently the consumer needs to have fallback logic, because it isn't apparent which encoding is transmitted: https://github.com/input-output-hk/cardano-wallet/blob/bb384f5f8e1ec13f248df46f835af7781d490932/lib/core/src/Cardano/Pool/Metadata.hs#L133-L135

It would be nicer to have something like:

```hs
newtype PoolId = HexPoolId { getPoolId :: Text }
               | BechpoolId { getPoolId :: Text }
```

With an appropriate tagged json encoding.

It appears this would be API breaking and the API needs to be incremented?

**Comment by ksaric** [comment]
Yes, in the sprint.

**Comment by ksaric** [comment]
Currently possible to send both formats as the pool id. Not increasing the API version since this is backward compatible. Implemented in - https://github.com/input-output-hk/smash/pull/123

**Comment by hasufell** [comment]
I don't see where the PR implements a *sum type* in servant. The servant types are untouched.

**Comment by ksaric** [comment]
It doesn't. But why add a sum type if all that's needed for it is in the PR?

**Comment by hasufell** [comment]
> It doesn't. But why add a sum type if all that's needed for it is in the PR?

Because the API doesn't tell you which one it is and you have to try to parse both (also complicating error handling/messages). I'm not sure if it's worth breaking the API, but that was the idea. I'll leave that to you.

**Comment by ksaric** [comment]
> > It doesn't. But why add a sum type if all that's needed for it is in the PR?
> 
> Because the API doesn't tell you which one it is and you have to try to parse both (also complicating error handling/messages). I'm not sure if it's worth breaking the API, but that was the idea. I'll leave that to you.

You don't have to parse both. The current format can parse both formats from the URL and you can pass that (HEX) or forward it to SMASH (either HEX or Bech32).
Once it is inside SMASH it is always HEX encoded.

**Comment by ksaric** [comment]
Or maybe I misunderstood the issue, we can have a quick call to discuss.

**Comment by hasufell** [comment]
>  Once it is inside SMASH it is always HEX encoded.

Ah, so the API endpoints only return HEX encoded, but accept both HEX and Bech32?

**Comment by ksaric** [comment]
> > Once it is inside SMASH it is always HEX encoded.
> 
> Ah, so the API endpoints only return HEX encoded, but accept both HEX and Bech32?

Yes, exactly.

**Comment by hasufell** [comment]
I think that's ok too then for the wallet.
