### ISSUE TITLE
Provide OpenAPI spec?

### ISSUE THREAD

**Issue by hasufell** [input-output-hk/smash#120]
I think it would be useful to have it and have a guarantee that the servant types match the spec. There are generally 3 approaches:

1. write the OpenAPI spec manually and run schema [tests against the types](https://hackage.haskell.org/package/servant-openapi3-2.0.1.0/docs/Servant-OpenApi.html#g:4) (what cardano-wallet currently does, works quite well)
2. generate the openapi spec from servant via https://hackage.haskell.org/package/servant-openapi3-2.0.1.0/docs/Servant-OpenApi.html#g:2
3. generate servant types from openapi spec

That allows to be language agnostic and have a nice online API documentation like [this](https://input-output-hk.github.io/cardano-wallet/api/edge/).

**Comment by ksaric** [comment]
There is an issue in the sprint about improving existing Swagger documentation. We already have Swagger. If need be, we can move to 2.

**Comment by ksaric** [comment]
The OpeanAPI spec for Servant is not yet mature enough and requires quite a bit of dependency, so currently improved the existing Swagger docs - https://github.com/input-output-hk/smash/pull/130

**Comment by hasufell** [comment]
Sorry, but can you point me to the actual swagger definition file? I cannot find it.

**Comment by ksaric** [comment]
> Sorry, but can you point me to the actual swagger definition file? I cannot find it.

You need to run SMASH and then go to `/swagger.json`. For example - https://smash.cardano-mainnet.iohk.io/swagger.json

**Comment by hasufell** [comment]
Right... that doesn't let us track changes easily... my idea was that the swagger spec is commited to the repository.

**Comment by ksaric** [comment]
> Right... that doesn't let us track changes easily... my idea was that the swagger spec is commited to the repository.

Ideally, we would build it in CI and persist it somewhere, but if you need to have it in the repo, I can add one.
