### ISSUE TITLE
Create directory for --state-dir automatically if it does not exist

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/smash#131]
**db-sync** creates directory for `--state-dir` automatically if it does not exist - maybe this could be done for smash too ? 

I ran:

`SMASHPGPASSFILE=./config/pgpass cabal run smash-exe -- run-app-with-db-sync --config config/shelley-qa-config.yaml --socket-path ../cardano-node/state-node-shelley_qa/node.socket --schema-dir schema/ --state-dir ledger-state/shelley_qa`

and got this error:

> [smash-node:Error:40] [2020-12-14 13:20:25.88 UTC] ChainSyncWithBlocksPtcl: ledger-state/shelley_qa: getDirectoryContents:openDirStream: does not exist (No such file or directory)
> [smash-node.Mux:Info:37] [2020-12-14 13:20:25.88 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "state-node-shelley_qa/node.socket"} event: State: Dead
> [smash-node.Mux:Notice:37] [2020-12-14 13:20:25.88 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "state-node-shelley_qa/node.socket"} event: Miniprotocol MiniProtocolNum 5 InitiatorDir terminated with exception ledger-state/shelley_qa: getDirectoryContents:openDirStream: does not exist (No such file or directory)
> [smash-node.Subscription:Error:36] [2020-12-14 13:20:25.88 UTC] [String "Application Exception: LocalAddress \"../cardano-node/state-node-shelley_qa/node.socket\" ledger-state/shelley_qa: getDirectoryContents:openDirStream: does not exist (No such file or directory)",String "SubscriptionTrace"]
> [smash-node.ErrorPolicy:Error:16] [2020-12-14 13:20:25.88 UTC] [String "ErrorPolicyUnhandledApplicationException ledger-state/shelley_qa: getDirectoryContents:openDirStream: does not exist (No such file or directory)",String "ErrorPolicyTrace",String "LocalAddress \"../cardano-node/state-node-shelley_qa/node.socket\""]

It disappeared after I created manually **ledger-state/shelley_qa** directories

**Comment by ksaric** [comment]
Implemented in https://github.com/input-output-hk/smash/pull/132
