### ISSUE TITLE
Failed to build smash-servant-types-1.3.0

### ISSUE THREAD

**Issue by btbf** [input-output-hk/smash#135]
cabal build smash

src/Cardano/SMASH/Types.hs:341:26: error:
    • No instance for (MonadFail (Either Text))
        arising from a use of ‘parseTimeM’
    • In the expression: parseTimeM False defaultTimeLocale timeFormat
      In the expression:
        parseTimeM False defaultTimeLocale timeFormat $ toS queryParam
      In an equation for ‘parsedTime’:
          parsedTime
            = parseTimeM False defaultTimeLocale timeFormat $ toS queryParam
    |
341 |             parsedTime = parseTimeM False defaultTimeLocale timeFormat $ toS queryParam
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build smash-servant-types-1.3.0 (which is required by
test:smash-test from smash-1.3.0, exe:smash-exe from smash-1.3.0 and others).

Cabal:3.2.0.0
GHC:8.10.2
Ubuntu:20.04

**Comment by erikd** [comment]
This builds for me which suggests that `cabal update` will probably fix this.

**Comment by btbf** [comment]
I ran cabal update, but it didn't help. I get the same error.

**Comment by erikd** [comment]
Ok, I was wrong. @ksaric can sort this out. I suspect its got something to do with package versions.

**Comment by ksaric** [comment]
@btbf Will look into it and get back to you soon.

**Comment by ksaric** [comment]
@btbf I looked into it. I didn't find any issues building with `cabal` (using `cabal build smash`). Tried it both on `master` and on `release-1.3.0` (`1.3.0` tag). 

Using Cabal version `3.2.0.0`. Also, if such an error was present, it would probably be visible in CI, since our CI builds on Cabal.

Please provide more information or try building using `stack` or `Nix`.

**Comment by ksaric** [comment]
Will close for now, please reopen if you find more information. Thanks.

**Comment by ksaric** [comment]
@btbf You might try `cabal clean` first and then build it.

**Comment by ksaric** [comment]
Also, it might be an issue with GHC version. Will look into it tomorrow and report back.
