### ISSUE TITLE
SMASH not returning active pools that were previously retired

### ISSUE THREAD

**Issue by spirestaking** [input-output-hk/smash#138]
We recently re-registered a pool that was previously retired.  The pool is showing active on various sites including pooltool.io, cardanoscan.io and adapools.org (including active stake) and the metadata hash is correct.  We were also able to successfully delegate to the pool using Yoroi to confirm the protocol supports reactivated pools.  However, the pool does not show in Daedalus because SMASH returns a 404 error:

Pool ID: 248a66f38e131b6c3b6ade0a639622068f537824edeb2e9c5b107e86

SMASH query for the pool:
https://smash.cardano-mainnet.iohk.io/api/v1/metadata/248a66f38e131b6c3b6ade0a639622068f537824edeb2e9c5b107e86/3bbf756c4d210e5309c3d922e768800738f47d96648d3d80f108e5a422b3ddd1

SMASH doesn't return a handled error either:
https://smash.cardano-mainnet.iohk.io/api/v1/errors/248a66f38e131b6c3b6ade0a639622068f537824edeb2e9c5b107e86

**Comment by ksaric** [comment]
@spirestaking Looking into it.
The pool is retired and can be found here - https://smash.cardano-mainnet.iohk.io/api/v1/retired
The idea of somebody "reviving" a pool is something that had not occurred to me.

**Comment by spirestaking** [comment]
Can you please advise regarding this use case so we can determine whether we should wait for a SMASH update or register a new pool?  It appears SMASH may be the only component that is preventing the pool from being fully operational/visible.  Much appreciated.

**Comment by ksaric** [comment]
@spirestaking A new pool will certainly work, will report more details about the current situation and possible fix in about 30 minutes.

**Comment by ksaric** [comment]
@spirestaking So I'm prioritizing the fix for this now, but the fix will be included in the new release and then the release will have to be deployed to the active SMASH servers.
If you don't want to wait for next week for the fix to be included, _please create a new pool_. Thank you.

**Comment by spirestaking** [comment]
Thank you for the prompt response and resolution.  Much appreciated!

**Comment by ksaric** [comment]
Implemented in https://github.com/input-output-hk/smash/pull/140, will be in the new release, will post a comment when the release is available/deployed.

**Comment by ksaric** [comment]
Implemented and released in https://github.com/input-output-hk/smash/releases/tag/v1.4.0, will be deployed soon.
