### ISSUE TITLE
implement metadata files hashing to purge cache like browsers do

### ISSUE THREAD

**Issue by gacallea** [input-output-hk/smash#141]
Hi Team :) 

Feature request/Enhancement for SMASH:

I've recently updated my pool's metadata files, with the same file names, and SMASH is still pointing/caching the old metadata.

SMASH should implement a mechanism similar to what web browsers do with static assets, to favor the newest metadata when file names stay the same.

E.g: hashing of metadata files like browsers do with any static asset. And purge the cache to fetch the latest data (when the file has changed but not the file name). 

Please and thank you

Andrea, SALAD.

**Comment by ksaric** [comment]
Hi @gacallea.

The metadata endpoint is tied to two things:
- the pool id
- the metadata hash (the hash of the actual file)

The old metadata is still present in the history of the blockchain and thus exists.
The new metadata is in the new URL, since it's hash has changed and it should be in a new location.

There are some issues with what you are proposing.
Based on what criteria should you "purge" the metadata? Pool id and what?
Now, why you would want this to be something to be implemented is more interesting to me than just this observation/issue.

**Comment by gacallea** [comment]
Hi @ksaric 

thank you for the kind reply and for the details. If SMASH already hashes the files, does this mean that a new metadata file with the same path & name but different data within the files should be picked up automatically? If that's the current behavior, it's exactly what I was trying to propose.

Anyway, I'm not sure what I proposed would work, but I thought about asking since my pool new metadata isn't being picked up by SMASH.

My situation is (change of both path and content inside the files):

- Old metadata

```https://insalada.io/SALAD.metadata.json``` + ```https://insalada.io/SALAD.extended-metadata.json```

- New metadata

```https://insalada.io/.well-known/SALAD.metadata.json``` + ```https://insalada.io/.well-known/SALAD.extended-metadata.json```

Perhaps SMASH is picking up the old ones and ignores the new ones because of that? I left the old in place because I feared to "break something" and disappear from Daedalus, as a transitional measure. I was planning to remove the old data once the new one was in place, but this never happened.

Thank you

**Comment by ksaric** [comment]
> If SMASH already hashes the files, does this mean that a new metadata file with the same path & name but different data within the files should be picked up automatically? If that's the current behavior, it's exactly what I was trying to propose.

Once the value of the metadata is changed, the hash is changed. So the hash of https://raw.githubusercontent.com/input-output-hk/smash/master/test_pool.json is not the same if you change that content. For more info, you can check out https://docs.cardano.org/projects/smash/en/latest/getting-started/how-to-install-smash.html#how-to-figure-out-the-json-hash

The target of the "homepage" is not what is being included in the hash.

> Anyway, I'm not sure what I proposed would work, but I thought about asking since my pool new metadata isn't being picked up by SMASH.

I'm not sure what is it that you want to happen. If you have the same file, and you do, there are no changes. 
What changes do you want to happen? What is it that you expect would happen?

**Comment by gacallea** [comment]
OK, let's start over. Apologies for a confusing feature request without knowing the SMASH internals I kinda made a mess in my request. I'll describe the current issue more than the proposed request, perhaps this way it is clearer what the goal is.

The problem: I wanted to change metadata files PATH and DATA in a safe way, so that SMASH picked it up and my pool didn't disappear from Daedalus. As of now, the OLD metadata is gone, the NEW one is in place.

- Old metadata

```https://insalada.io/SALAD.metadata.json``` + ```https://insalada.io/SALAD.extended-metadata.json```

- New metadata

```https://insalada.io/.well-known/SALAD.metadata.json``` + ```https://insalada.io/.well-known/SALAD.extended-metadata.json```

This happened:

- pooltool, adapools, adatstat, pool.pm and similar projects have picked up the NEW metadata just fine
- SMASH has NOT.
- SALAD is GONE from Daedalus

The above scenario is what I wanted to avoid!!! I may not know the internal of SMASH, so my request may have sounded silly, but the above is a fact, and my pool is gone from Daedalus.

Now, any hashing, cache purging or whatever necessary is for SMASH to pick up new metadata has failed. Please fix/look into this. I'm not able to formulate the feature request, but I hope that these new details can help understand the issue why I proposed it in the first place.

**Comment by gacallea** [comment]
closing this "feature" request. It is based on wrong assumptions and poor understanding of SMASH. new registration went fine, and now SALAD is back in Daedalus. Apologies for the confusion, I was just trying to help.

**Comment by ksaric** [comment]
No, problem, @gacallea, glad to help out and clear any misunderstandings.
