### ISSUE TITLE
--state-dir parameter is mandatory but it is not documented

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/smash#144]
If you start Smash as described in the documentation, you would get the below error:

```
SMASHPGPASSFILE=./config/pgpass stack run smash-exe -- run-app-with-db-sync --config config/launchpad-config.yaml --socket-path ../launchpad/db/node.socket --schema-dir schema/
Missing: --state-dir FILEPATH
Usage: smash-exe run-app-with-db-sync --config FILEPATH --socket-path FILEPATH
                                      --state-dir FILEPATH --schema-dir FILEPATH
                                      [--rollback-to-slot WORD]
  Run the application that syncs up the pool info and serves it.
```

- smash documentation: https://docs.cardano.org/projects/smash/en/latest/getting-started/how-to-install-smash.html#how-to-run-smash-with-the-cardano-node

**Comment by ksaric** [comment]
This will be documented in the new version, when we release it. 
The issue with documentation is that it is deployed once we release it, not before.

If the new documentation lacks something, you can open a new issue. Thanks.
