### ISSUE TITLE
Feature Request: url hook to trigger automated refresh of front-end cache

### ISSUE THREAD

**Issue by johnalotoski** [input-output-hk/smash#148]
* A url webhook option in smash to enable selective automated refresh of the front end cache would permit:
  * Long front-end cache lifetimes to keep load on smash low
  * Dynamic automated front-end cache updates which only update changing pieces of metadata, as the changes occur in smash

* If an optional smash webhook base URL parameter is supplied upon smash startup where:
  * An example webhook base URL parameter would be:
    * BASE=https://$SMASH_FQDN/api
  * The API webhook would be issued as a get in a curl compatible manner to:
    * curl -XGET $BASE/v1/{metadata/$POOL/$HASH, delisted, ...}

* Smash would then take the following additional webhook action with each of the following endpoint calls:
  
  * PATCH Enlist API:
    * Webhook call all affected new $POOL and $HASH attributes:
      * curl -XGET $BASE/v1/metadata/$POOL/$HASH (overall appropriate combinations)
      * This will prevent previously cached 404s from before pool addition
  
  * PATCH Delist API:
    * Webhook call all affected delisted $POOL and $HASH attributes:
      * curl -XGET $BASE/v1/metadata/$POOL/$HASH (over all appropriate combinations)
      * This will prevent previously cached 200s from before pool deletion
    * Also call:
      * curl -XGET $BASE/api/v1/delisted
      * This will prevent an outdated delisted front-end cache response

  * POST Insert Pool metadata (POST api/v1/metadata):
    * Webhook call all affected pool data inserts to $POOL and $HASH attributes:
      * curl -XGET $BASE/v1/metadata/$POOL/$HASH (over all appropriate combinations)
      * This will prevent previously cached 404s from before pool metadata insertion

**Comment by ksaric** [comment]
This has been superseded by https://github.com/input-output-hk/smash/pull/153
