### ISSUE TITLE
Servers return `200 OK` when metadata isn't found 

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/smash#16]
Testing on the version currently deployed for the shelley testnet:

```console
$ curl -v https://smash.shelley-testnet.dev.cardano.org/api/v1/metadata/invalid
< HTTP/2 200 
< server: nginx
< date: Thu, 09 Jul 2020 14:04:01 GMT
< content-type: application/json;charset=utf-8
< vary: Accept-Encoding
{"code":"DbLookupTxMetadataHash","description":"The hash invalid is missing from the DB."}
```

This goes quite against one's intuition & REST practices in general. What about having the server returns a `404` so that clients can adjust their behavior based on the response's code.

**Comment by piotr-iohk** [comment]
Is this fix deployed to the shelley-testnet SMASH? I see that:
```
$ curl -v https://smash.shelley-testnet.dev.cardano.org/api/v1/metadata/invalid

< HTTP/2 200 
< server: nginx
< date: Wed, 15 Jul 2020 12:52:26 GMT
< content-type: application/json;charset=utf-8
< vary: Accept-Encoding

```

**Comment by ksaric** [comment]
@piotr-iohk I would need confirmation from DevOps for that, but the redeploy is going to happen soon anyway (day or two away) so I can notify you when the redeploy is complete.

**Comment by ksaric** [comment]
I can confirm this works locally, when the new version is deployed it will work.

**Comment by ksaric** [comment]
@piotr-iohk The latest release (https://github.com/input-output-hk/smash/releases/tag/untagged-568b27b3771d5f884c30) contains the fix and will be deployed by DevOps. When that is complete, you will see the correct behavior.
