### ISSUE TITLE
Exceptions into logs

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/smash#49]
Ideally, there should not be any exceptions into the logs. Anyway, the server still works/seems to not be affected.

```
[smash-node.fetch:Warning:38] [2020-08-10 13:53:47.43 UTC] HTTP Exception: InternalException (HandshakeFailed (Error_Protocol ("certificate rejected: [NameMismatch \"metadata.coolpool.io\"]",True,CertificateUnknown)))
```

**Comment by ksaric** [comment]
This is just a name of the exception that occurred, it is translated into an error, so this is correct.

**Comment by ksaric** [comment]
Closing now since it's improved by https://github.com/input-output-hk/smash/pull/94
