### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/smash#50]
1. it would be useful to have a note specifying that all the stack commands can be run also with cabal
2. Inserting pool metadata
    - add a note specifying that the json file should be local (it cannot be a file from the internet)
    - prepend the command with SMASHPGPASSFILE=config/pgpass
3. add examples for smash operator:
- list stake pool delisted by mistake (this is a workaround and needs to be documented well)

**Comment by ksaric** [comment]
Closing, fixed in https://github.com/input-output-hk/smash/pull/137
