### ISSUE TITLE
pool_id delist endpoint is returning 200 for any string (not only for valid pool_ids)

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/smash#51]
Delist endpoint should validate that pool_id exists before delisting.

Scenario: smash user delists a wrong pool_id (by mistake) believing that the correct pool_id was delisted.

````
$ curl -X PATCH -v http://localhost:3100/api/v1/delist -H 'content-type: application/json' -d '{"poolId": "aaa"}'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3100 (#0)
> PATCH /api/v1/delist HTTP/1.1
> Host: localhost:3100
> User-Agent: curl/7.58.0
> Accept: */*
> content-type: application/json
> Content-Length: 17
> 
* upload completely sent off: 17 out of 17 bytes
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Date: Tue, 11 Aug 2020 08:24:44 GMT
< Server: Warp/3.3.13
< Content-Type: application/json;charset=utf-8
< 
* Connection #0 to host localhost left intact
{"poolId":"aaa"}
```

**Comment by AndrewWestberg** [comment]
Same issue for the errors endpoint. It returns 200 response even for a bad pool id.

curl -X GET -v https://smash.cardano-testnet.iohkdev.io/api/v1/errors\?poolId\=bogus_pool_id

**Comment by ksaric** [comment]
This is fixed in https://github.com/input-output-hk/smash/pull/124, will be included in the next release.

**Comment by AndrewWestberg** [comment]
@ksaric Do you know when this next release will get deployed to production and testnet?

**Comment by ksaric** [comment]
@AndrewWestberg Next week.
