### ISSUE TITLE
Cannnot get metadata of pool 89eba2781e5cd11ccda6be56503702a39e9941e522f04cd5bba22957

### ISSUE THREAD

**Issue by leo42** [input-output-hk/smash#53]
When looking up my staking pool with the ID : 89eba2781e5cd11ccda6be56503702a39e9941e522f04cd5bba22957

An error shows up and no information about the pool is displayed

Issue found using  Yoroi  all other pool IDs i check are loading fine. 

Please advice if i can help resolve this issue in any way.

**Comment by ksaric** [comment]
Can you provide more information?
If you can access it from the Daedalus, it usually means that it's loaded from SMASH correctly.

**Comment by leo42** [comment]
Yes it shows up in Daedalus.

sorry turns out it was a Yoroi issue with parsing the SRV record of my relays.

Thank you for your response i am closing the issue now.
