### ISSUE TITLE
Easily query reason for pool metadata lookup failure

### ISSUE THREAD

**Issue by SebastienGllmt** [input-output-hk/smash#57]
Background:
* Yoroi uses SMASH to populate metadata for stake pools.
* When Yoroi fails to lookup a pool in SMASH, we instead show "Unknown pool"

We often get pool operators messaging us asking why their pool shows up as "unknown pool" in Yoroi. The best we can do right now is tell to double-check their metadata and how it's hosted, but that's not a great response. It would be nice if there was a way for pool operators to easily test if SMASH can read their pool metadata and, if not, give an error message

**Comment by ksaric** [comment]
This was implemented, please check https://github.com/input-output-hk/smash/blob/master/doc/getting-started/how-to-install-smash.md#checking-the-pool-rejection-errors
