### ISSUE TITLE
Add compatibility info to README

### ISSUE THREAD

**Issue by tatyanavych** [input-output-hk/smash#71]
To ensure correct compatibility with components Smash depends on, please, create compatibility matrix for released versions (e.g. as in https://github.com/input-output-hk/cardano-wallet/blob/master/README.md#latest-releases).

smash | cardano-node | ?
----------------------------
1.1.0 | ?
1.0.1 | 1.18.0
1.0.0 | 1.18.0

**Comment by savicsava** [comment]
Since we have only one instance of SMASH that we (as IOG) are maintaining for now, I really don't think we need to have a record of history on previous versions of SMASH until we start having multiple instances.

**Comment by ksaric** [comment]
Closing this, we have a compatibility matrix here - https://docs.cardano.org/en/latest/release-information/comp-matrix.html
