### ISSUE TITLE
The 'cause' inside the /errors response could be more explicit

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/smash#73]
At this moment when the metadata is not available, "cause":"HTTP Response : 404" but it can be more explicit like ``metadata file is not available/reachable`

**Comment by dorin100** [comment]
"cause":"HTTP Response : 404" also when the metadata_hash is not correct when registering the pool

**Comment by ksaric** [comment]
Closing, implemented in https://github.com/input-output-hk/smash/pull/94
