### ISSUE TITLE
no information on 404

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/smash#77]
Smash should give some error information on 404

For example:

404: pool id not found
404: metadata hash mismatch
404: url https://yourpool.com/foo.json unreachable
404: pool delisted

**Comment by ksaric** [comment]
The errors are covered in the `error` endpoint further implemented by https://github.com/input-output-hk/smash/pull/94
The errors are clear and easy to read and include all the information about specific pools.
It would duplicate the effort and make things more complicated.

For example, you would need to search for an invalid hash to find the error about metadata hash mismatch.
