### ISSUE TITLE
smash doesn't retry on metadata connection failure

### ISSUE THREAD

**Issue by mmahut** [input-output-hk/smash#84]
Looks like smash doesn't retry to fetch the metadata until the next rescan/restart if the connection times out or closes. 

```
Sep 28 12:03:11 smash2 rf6l2nxbvb6al7nh853h21r4yg2p7rbj-smash[820]: [smash-node:Info:2034603] [2020-09-28 12:03:11.52 UTC] Request: https://mantispool.net/poolmeta.json
Sep 28 12:03:11 smash2 rf6l2nxbvb6al7nh853h21r4yg2p7rbj-smash[820]: [smash-node:Warning:2034603] [2020-09-28 12:03:11.53 UTC] Connection failure
```

Would be nice if smash did retry this operation.

**Comment by ksaric** [comment]
@mmahut The connection failure is one of the conditions in which the SMASH server does retry. Can you check if the metadata is actually in the SMASH server or simply check https://docs.cardano.org/projects/smash/en/latest/getting-started/how-to-install-smash.html#checking-the-pool-rejection-errors for errors?

Thanks, reopen if you find an issue.
