### ISSUE TITLE
Database connection inconsistency

### ISSUE THREAD

**Issue by mesudip** [input-output-hk/smash#88]
I had postgres server already running at port `5432`, So id decided to spwan up a new postgres server at port `5433` for test purpose.
with configuration  `localhost:5433:smash:smash:smash`
I got following error
```
Running : migration-1-0000-20200610.sql
psql: fe_sendauth: no password supplied
```
I checked twice, thrice. i even tried with random configurations. I found that providing wrong database name would succeed in authentication but fail with message
```
smash-exe: libpq: failed (FATAL:  database "testdb" does not exist 
```
The guess the culprit code is the code that executes migration. You can see that the **password is not passed here and neither is port**.
I tried with `PGPASSWORD` environment variable but since the port is not specified here, it was connecting to my another postgres instance.

```.hs
    -- This assumes that the credentials for 'psql' are already sorted out.
    -- One way to achive this is via a 'PGPASSFILE' environment variable
    -- as per the PostgreSQL documentation.
    let command =
          List.intercalate " "
            [ "psql"
            , BS.unpack (pgcDbname pgconfig)
            , "--no-password"
            , "--quiet"
            , "--username=" <> BS.unpack (pgcUser pgconfig)
            , "--host=" <> BS.unpack (pgcHost pgconfig)
            , "--no-psqlrc"                     -- Ignore the ~/.psqlrc file.
            , "--single-transaction"            -- Run the file as a transaction.
            , "--set ON_ERROR_STOP=on"          -- Exit with non-zero on error.
            , "--file='" ++ script ++ "'"
            , "2>&1"                            -- Pipe stderr to stdout.
            ]
```

It was solved when I used the database on standard port.

**Comment by erikd** [comment]
Please try adding something like:
```
    , "--port=" <> show (pgcPort pgconfig)
```
directly after the `--host` line.

**Comment by ksaric** [comment]
@mesudip You can try running it on this branch which contains the changes @erikd mentioned - https://github.com/input-output-hk/smash/tree/ksaric/SMASH-88

**Comment by ksaric** [comment]
Fixed in https://github.com/input-output-hk/smash/pull/133
