### ISSUE TITLE
Build problems with cabal

### ISSUE THREAD

**Issue by hasufell** [input-output-hk/smash#91]
prior to this commit https://github.com/input-output-hk/ouroboros-network/commit/b6d51e74568f7fb3cef1d02a4ad55a124de9ca6f this repo isn't buildable properly with cabal

This was also reported by @ksaric on slack.

Error log is here: https://gist.github.com/hasufell/a724167782e126fede9043867b2ce563

```
cabal: filepath wildcard 'ChangeLog.md' does not match any files.
```

A bump to that commit seems is a long jump, so someone should confirm that or we create a branch in ouroboros-network that only contains this commit: https://github.com/input-output-hk/ouroboros-network/compare/f0eb6e439e7c0121476ded5e88d2f638e8aa36ac..b6d51e74568f7fb3cef1d02a4ad55a124de9ca6f

**Comment by ksaric** [comment]
I can confirm that by switching to that commit, the cabal install actually works:
```
creating /usr/local/bin
Copying 'smash-exe'
```
Thanks for finding the issue, @hasufell!

**Comment by hasufell** [comment]
I have more build problems on master:

```
[2 of 3] Compiling Main             ( chairman/chairman.hs, /home/jule/git/iohk/smash-2/dist-newstyle/build/x86_64-linux/ghc-8.6.5/cardano-node-1.19.0/x/chairman/build/chairman/chairman-tmp/Main.o )

chairman/chairman.hs:40:20: error:
    Variable not in scope:
      parseNodeConfigurationFP :: ConfigYamlFilePath -> IO a0
   |
40 |     nc <- liftIO $ parseNodeConfigurationFP caConfigYaml
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^

chairman/chairman.hs:42:57: error:
    Variable not in scope: ncProtocol :: a0 -> Protocol
   |
42 |     let someNodeClientProtocol = mkNodeClientProtocol $ ncProtocol nc
   |                                                         ^^^^^^^^^^
```

plan.json is here https://gist.github.com/hasufell/f2aded17d262504d3f6092cde2ce4e8e

**Comment by ksaric** [comment]
Weird. What branch? It built fine for me after I fixed that issue.

**Comment by hasufell** [comment]
> Weird. What branch? It built fine for me after I fixed that issue.

master, with cabal-3.2 (which doesn't need the fix yet). I'm currently trying to regenerate the cabal.project via stack2cabal, but there was a minor bug causing issues: https://github.com/hasufell/stack2cabal/issues/30

**Comment by ksaric** [comment]
This currently works.
