### ISSUE TITLE
Health check endpoint

### ISSUE THREAD

**Issue by hasufell** [input-output-hk/smash#92]
For https://jira.iohk.io/browse/ADP-496 it would be interesting to have an inexpensive and unambiguous health check endpoint.

I couldn't find any in https://github.com/input-output-hk/smash/blob/master/src/Lib.hs

**Comment by ksaric** [comment]
There is a health check endpoint using Prometheus - https://github.com/input-output-hk/smash/blob/master/src/Cardano/Metrics.hs
Called from - https://github.com/input-output-hk/smash/blob/bd36af66b64d6ee1f81a1c4f44b97597cb15d411/src/Cardano/SmashDbSync.hs#L407

So by default, you have port 8080 as the health check port (`http://localhost:8080/`), not sure if it's exported through the HTTP proxy:
```
# TYPE action_queue_length_post gauge
action_queue_length_post  0.0
# TYPE action_queue_length_post_write gauge
action_queue_length_post_write  748.0
# TYPE action_queue_length_pre gauge
action_queue_length_pre  0.0
# TYPE db_block_height gauge
db_block_height  4820725.0
# TYPE remote_tip_height gauge
remote_tip_height  4822338.0
```

**Comment by hasufell** [comment]
But does that tell me this is a an actual smash server and it understands my API calls?

**Comment by ksaric** [comment]
> But does that tell me this is a an actual smash server and it understands my API calls?

No, the SMASH server tells you it's a SMASH server by understanding your API calls :smile: 

What is that you want to check here?
A call which results in?

**Comment by hasufell** [comment]
> No, the SMASH server tells you it's a SMASH server by understanding your API calls smile

We want to have a health check when a user sets a SMASH server, knowing that it's a valid SMASH server without doing expensive API calls and validating this prior to any metadata syncing.

**Comment by ksaric** [comment]
@hasufell Sure, propose the format of such health check.

**Comment by hasufell** [comment]
```yaml
paths:
  /status:
    get:
    summary: Get
    description:  Query status/health of the SMASH server
    responses:
      200:
        description: Ok
        content:
          application/json:
            schema:
              type: object
              required:
                - smash_status
                - smash_version
             properties:
               smash_status:
                 description: the status of the SMASH server
                 type: string
                 enum:
                   - ok
                   - booting
                 example: ok
               smash_version:
                 description: The "git describe" version of the SMASH server
                 type: string
                 example: 0.1.0-rc-99-gb7fa2fe
               smash_message:
                 description: A custom message set by the operator
                 type: string
                 example: I'm a SMASH server for cardano
```

1. whether `booting` makes sense or not as a value, I don't know, it's optional I guess
2. I'm avoiding generic `status` field, so we can identify from the object keys that it's a smash server

**Comment by ksaric** [comment]
@hasufell That looks solid, will implement it in this sprint, and get back to you.

**Comment by ksaric** [comment]
Implemented in https://github.com/input-output-hk/smash/pull/101

**Comment by hasufell** [comment]
many thanks
