### ISSUE TITLE
Multiple Metadata entry for same Stake Pool

### ISSUE THREAD

**Issue by mesudip** [input-output-hk/smash#95]
```
Version: 6cfba0b5f17e7eec648972ec4a7a173ad9b29851
```
The result is for a pool with ticker "ADA" and there are 3 entries for it in the database. Each of the entries has a unique value for `extended`. 

I am not sure if it's was as intended to keep the history of metadata change, but it would be better to have a single, latest entry for each StakePool.
```
 "data": [
    {
      "name": "Cardano24",
      "description": "Want to do HighProfit-Investments/Delegations to a Pool with: DOS/DDOS-Protection, 10Gbit/s per Server, High-Availability-Infrastructure with Juniper Routers/Firewalls? EARN MONEY with us while we SUPPORT the COMMUNITY! Thanks! https://Cardano24.com",
      "ticker": "ADA",
      "homepage": "https://cardano24.com",
      "extended": "https://cardanostakehouse.com/125e22de-bff9-4097-b83e-b54.json",
      "pool_hash": "be6d07b366b26dd577682e0e499c0d81988d8b3f49b52b853691eeba"
    },
    {
      "name": "Cardano24",
      "description": "Want to do HighProfit-Investments/Delegations to a Pool with: DOS/DDOS-Protection, 10Gbit/s per Server, High-Availability-Infrastructure with Juniper Routers/Firewalls? EARN MONEY with us while we SUPPORT the COMMUNITY! Thanks! https://Cardano24.com",
      "ticker": "ADA",
      "homepage": "https://Cardano24.com",
      "extended": "https://cardanostakehouse.com/5307de75-ce0b-47e4-ab15-bd5.json",
      "pool_hash": "be6d07b366b26dd577682e0e499c0d81988d8b3f49b52b853691eeba"
    },
    {
      "name": "Cardano24",
      "description": "Cardano24 - Let us shape our future with humanity in mind! Be a part of us - be a part of our future!",
      "ticker": "ADA",
      "homepage": "https://cardano24.com",
      "pool_hash": "be6d07b366b26dd577682e0e499c0d81988d8b3f49b52b853691eeba"
    }
]
  ```

**Edit**

I am directly using the database used by smash and not it's api

**Comment by ksaric** [comment]
@mesudip What do you get back when you actually query the API?

**Comment by mesudip** [comment]
With API I get the unique result because the API is `api/v1/metadata/<POOL_ID>/<POOL_HASH>`. Each of the above result has a unique metadataHash. So it returns unique result when including metadata hash.

But I need to implement searching metadata by `ticker_name`. In this case, there are multiple results, but in fact there can be only one pool with that ticker name.

**Comment by ksaric** [comment]
@mesudip Please note that there is a API call `api/v1/tickers` which takes a ticker name and a pool hash, which solidifies the ticker name for that pool hash only. Ticker names are NOT unique.
